// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WpfApp1.Data;

namespace WpfApp1.Migrations
{
    [DbContext(typeof(PeopleContext))]
    [Migration("20211111104948_initlite")]
    partial class initlite
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.12");

            modelBuilder.Entity("Hello_World.Model.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mesto")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ulice")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("Hello_World.Model.Auto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Barva")
                        .HasColumnType("TEXT");

                    b.Property<double>("NajeteKilometry")
                        .HasColumnType("REAL");

                    b.Property<int?>("PersonId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RegistracniZnacka")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("Hello_World.Model.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AdresaDomovId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DatumNarozeni")
                        .HasColumnType("TEXT");

                    b.Property<string>("KrestniJmeno")
                        .HasColumnType("TEXT");

                    b.Property<string>("Prijmeni")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AdresaDomovId");

                    b.ToTable("People");
                });

            modelBuilder.Entity("Hello_World.Model.Auto", b =>
                {
                    b.HasOne("Hello_World.Model.Person", null)
                        .WithMany("OsobniAuta")
                        .HasForeignKey("PersonId");
                });

            modelBuilder.Entity("Hello_World.Model.Person", b =>
                {
                    b.HasOne("Hello_World.Model.Address", "AdresaDomov")
                        .WithMany()
                        .HasForeignKey("AdresaDomovId");

                    b.Navigation("AdresaDomov");
                });

            modelBuilder.Entity("Hello_World.Model.Person", b =>
                {
                    b.Navigation("OsobniAuta");
                });
#pragma warning restore 612, 618
        }
    }
}
